### ISSUE TITLE
future: text editor

### ISSUE THREAD

**Issue by cool-RR** [PythonTurtle/PythonTurtle#38] opened 2009-08-04 12:10 UTC

**Comment by bittner** [comment] 2019-03-31 19:31
This would be replicating what [IDLE](https://docs.python.org/3/library/idle.html) provides. Maybe we could come up with some very different, equally useful feature!

For example, how about "Show commands I typed", which may bring up a text editor window that shows all the commands the user typed into the interpreter since when she/he started the application. It could optionally also provide the possibility to save the text as a Python source code file.

I'm not sure how easy (or if possible at all) it is to do that, but it may solve some related feature requests, such as "save to a file" (mentioned on GgG, IIRC), "in-program editor" (#64) and "undo feature" (#11).

**Comment by bittner** [comment] 2020-02-07 09:24
This is probably a duplicate of #64.

**Closed by bittner** 2020-02-07 09:24 UTC
Labels: usabilty
